#! /usr/bin/env bash



if [[ $# -ge 1 ]] && [[ $1 = "-h" ]]
then
	echo -e "\nezgh : macros to manage GitHub repositories in a single command"
	echo "usage : ezgh <option> <args>"
	echo "available options : "
	echo "	-p <msg> pushes the current repo to main, with <msg> as the commit message"
	echo -e "	-b <name> creates a new branch with <name> as the branche's name\n"
	exit 0
fi

if [[ $# -eq 2 ]]
then
	if [[ $1 = "-p" ]]
	then
		git add .
		git commit -m "${2}"
		git push origin main
		echo -e "\nSuccessfully pushed current repo to main branch"
		exit 0
	fi

	if [[ $1 = "-b" ]]
	then
		git branch -a | if [[ $(grep -E ^"[\*\ ] ${2}"$) = "" ]]
		then
			git pull origin main
			git branch $2
			git add .
			git commit -m "ezgh : created branch ${2} and synced local repo to GitHub"
			git push origin $2
			echo -e "branch ${2} successfully created !"
		else
    		echo -e "\nezgh : a branch with that name already exists !!\n"
    		exit 1
		fi
		exit 0
	fi
fi

echo -e "\nezgh : this command was not formatted correctly"
echo -e "use \"ezgh -h\" to see all possible arguments\n"
exit 1
