#! /usr/bin/env bash

if [[ $# -ne 1 && $# -ne 2 ]]
then
    echo "lsrp_aux : fatal error : invalid arguments !"
    exit 1
fi

if [[ $# -eq 1 ]]
then
    np=$1
else
    np=$1$2
fi

for f in $(ls -pm1 $np | tr  " " "'" | tr "," " " | grep -v "/")
do
    if [[ $(echo $f | grep "^'" | wc -l ) -ne 0 ]]
    then
    	tmp=$(echo "$(echo $f | tail -c +2)" | tr "'" " ")
    else
	tmp=$(echo "$f" | tr "'" " ")
    fi

    if [[ $(echo $tmp | grep " " | wc -l) -ne 0 ]]
    then
	echo "$np'$tmp'"
    else
	echo $np$tmp
    fi
done

for f in $(ls -pm1 $np | tr " " "'" | tr "," " " | grep "/$")
do
    if [[ $(echo $f | grep "^'" | wc -l ) -ne 0 ]]
    then
    	tmp=$(echo "$(echo $f | tail -c +2)" | tr "'" " ")
    else
    	tmp=$(echo "$f" | tr "'" " ")
    fi

    if [[ $(echo $tmp | grep " " | wc -l) -ne 0 ]]
    then
       	lsrp_aux $np $(echo "'$tmp'")
    else
    	lsrp_aux $np $tmp
    fi
done
